#!/usr/bin/env bash

print_until_comment() {
    local line
    while IFS= read -r line; do
        if [[ "$line" == " */" ]]; then
            break
        fi
        sed 's/^ \*//' <<< "$line"
    done
}

print_whole_file () {
    local file="$1";
    if ! shift; then
        return
    fi

    echo "<!---   THIS FILE IS AUTOMATICALLY GENERATED, DO NOT CHANGE IT BY HAND   --->"
    echo

    while IFS= read -r line; do
        if [[ "$line" == "/**" ]]; then
            print_until_comment
            break
        fi 
    done < $file
}

main () {
    print_whole_file cast.h > README.md
}

main "$@"
